version: '3.8'
services:
 model:
    build: ./model
    volumes:
      - model_volume:/model
    ports:
      - "5000:5000"

 app:
    build: ./app
    volumes:
      - model_volume:/model
      - app_volume:/app
    ports:
      - "8501:8501"
    depends_on:
      - model

volumes:
 model_volume:
 app_volume:
